[package]
name = "easygpg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.6.2"
crossterm = "0.19.0"
colored = "2.0"
mio = "0.8.11"