.\" Manpage for EasyGPG.
.\" Contact easygpg@jwt2706.ca to correct errors or typos.
.TH man 1 "06 May 2024" "1.0" "EasyGPG man page"
.SH NAME
EasyGPG \- encrypt and decrypt files or text
.SH SYNOPSIS
easygpg [-e] [-d] [-s] [--help] [-h]
.SH DESCRIPTION
EasyGPG is a command line tool to help simplify the process of encrypting and decrypting files or text with GPG. See source code here: (https://github.com/jwt2706/EasyGPG)
.SH OPTIONS
.TP
-e
Triggers the encryption process.
.TP
-d
Triggers the decryption process.
.TP
-s
Lists the your current public keys available.
.TP
--help or -h
Displays the help message.
.SH SEE ALSO
gpg(1)
.SH BUGS
Report bugs or issues here: (https://github.com/jwt2706/EasyGPG/issues)
.SH AUTHOR
jwt2706 (easygpg@jwt2706.ca)